language: c

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq apt-transport-https python-docutils gnupg curl
  - curl -sL https://packagecloud.io/varnishcache/varnish41/gpgkey | sudo apt-key add -
  - echo "deb https://packagecloud.io/varnishcache/varnish41/ubuntu/ trusty main" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get -q update
  - sudo apt-get install varnish varnish-dev


before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

compiler:
  - clang
  - gcc
